'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import maplibregl, { Map, Marker } from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';

type MetricKey='marketCap'|'revenue'|'operatingIncome'|'netIncome';
type Company={id:string;name:string;ticker:string;country:string;region:string;industry:string;lat:number;lng:number;accent:string;metrics:Record<number,Record<MetricKey,number|null>>};
const metricLabels:Record<MetricKey,string>={marketCap:'時価総額',revenue:'売上高',operatingIncome:'営業利益',netIncome:'純利益'};
const rates={USD:1,JPY:147.2,EUR:.86,CNY:7.13,KRW:1388,GBP:.74};
const symbols={USD:'$',JPY:'¥',EUR:'€',CNY:'CN¥',KRW:'₩',GBP:'£'};
const base=[
['nvidia','NVIDIA','NVDA','アメリカ','北米','半導体',37.37,-121.96,'#7CFF6B'],['apple','Apple','AAPL','アメリカ','北米','ソフトウェア',37.33,-122.01,'#8BA7FF'],['microsoft','Microsoft','MSFT','アメリカ','北米','ソフトウェア',47.64,-122.13,'#5DD4FF'],['alphabet','Alphabet','GOOGL','アメリカ','北米','ソフトウェア',37.42,-122.08,'#FFCA65'],['amazon','Amazon','AMZN','アメリカ','北米','小売',47.62,-122.34,'#FF9B55'],['meta','Meta','META','アメリカ','北米','ソフトウェア',37.48,-122.15,'#6E8EFF'],['broadcom','Broadcom','AVGO','アメリカ','北米','半導体',37.40,-121.98,'#BC8CFF'],['tesla','Tesla','TSLA','アメリカ','北米','自動車',30.22,-97.62,'#FF6B6B'],['jpm','JPMorgan Chase','JPM','アメリカ','北米','金融',40.76,-73.97,'#7DE0B1'],['walmart','Walmart','WMT','アメリカ','北米','小売',36.37,-94.21,'#68D9C4'],['eli','Eli Lilly','LLY','アメリカ','北米','医薬品',39.77,-86.16,'#FF86B7'],['aramco','Saudi Aramco','2222','サウジアラビア','中東','エネルギー',26.31,50.12,'#F4C95D'],['sap','SAP','SAP','ドイツ','欧州','ソフトウェア',49.29,8.64,'#72B7FF'],['asml','ASML','ASML','オランダ','欧州','半導体',51.44,5.48,'#B58CFF'],['novo','Novo Nordisk','NVO','デンマーク','欧州','医薬品',55.81,12.51,'#FF86B7'],['toyota','Toyota Motor','7203.T','日本','アジア','自動車',35.08,137.16,'#FF7171'],['sony','Sony Group','6758.T','日本','アジア','その他',35.46,139.62,'#C3A6FF'],['tel','Tokyo Electron','8035.T','日本','アジア','半導体',35.68,139.77,'#7CFF6B'],['tsmc','TSMC','TSM','台湾','アジア','半導体',24.78,121,'#67F5B7'],['samsung','Samsung Electronics','005930','韓国','アジア','半導体',37.26,127.03,'#81A1FF'],['tencent','Tencent','0700.HK','中国','アジア','ソフトウェア',22.54,114.06,'#5DD4FF'],['alibaba','Alibaba','BABA','中国','アジア','小売',30.19,120.19,'#FF9B55'],['byd','BYD','1211.HK','中国','アジア','自動車',22.60,114.05,'#FF7171'],['reliance','Reliance Industries','RELIANCE','インド','アジア','エネルギー',19.06,72.87,'#F4C95D'],['hdfc','HDFC Bank','HDB','インド','アジア','金融',19.17,72.87,'#7DE0B1']];
const caps=[4300,3900,3800,2500,2300,1900,1650,1050,820,790,760,1800,380,420,310,330,150,125,1200,360,690,280,155,210,185];
const revRatios=[.3,.31,.36,.14,.31,.08,.1,.09,.22,.86,.08,.25,.12,.08,.11,.9,.55,.09,.07,.45,.18,.48,.3,.42,.24];
const companies:Company[]=base.map((row,i)=>{const [id,name,ticker,country,region,industry,lat,lng,accent]=row as [string,string,string,string,string,string,number,number,string];const cap=caps[i],rev=cap*revRatios[i];const make=(f:number)=>({marketCap:cap*f,revenue:rev*f,operatingIncome:rev*.18*f,netIncome:rev*.14*f});return{id,name,ticker,country,region,industry,lat,lng,accent,metrics:{2023:make(.72),2024:make(.86),2025:make(1)}}});
function money(v:number|null,c:keyof typeof rates){if(v==null)return'—';const x=v*rates[c],local=c==='JPY'||c==='KRW';return`${symbols[c]}${(local?x/1000:x).toFixed(x>=100?0:1)} ${c==='JPY'?'兆円':c==='KRW'?'조원':'B'}`}
function radius(v:number|null,m:MetricKey){if(!v)return 0;return Math.max(9,Math.min(52,Math.sqrt(v)*.72*(m==='marketCap'?1:m==='revenue'?1.55:3.2)))}

export default function Home(){
 const mapNode=useRef<HTMLDivElement>(null),mapRef=useRef<Map|null>(null),markers=useRef<Marker[]>([]);
 const[year,setYear]=useState(2025),[metric,setMetric]=useState<MetricKey>('marketCap'),[industry,setIndustry]=useState('すべての業種'),[region,setRegion]=useState('すべての地域'),[currency,setCurrency]=useState<keyof typeof rates>('JPY'),[query,setQuery]=useState(''),[selected,setSelected]=useState(companies[0]);
 const filtered=useMemo(()=>companies.filter(c=>(industry==='すべての業種'||c.industry===industry)&&(region==='すべての地域'||c.region===region)&&`${c.name} ${c.ticker}`.toLowerCase().includes(query.toLowerCase())),[industry,region,query]);
 useEffect(()=>{if(!mapNode.current||mapRef.current)return;mapRef.current=new maplibregl.Map({container:mapNode.current,center:[12,23],zoom:1.35,minZoom:1,style:'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',attributionControl:false});mapRef.current.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-left');return()=>{mapRef.current?.remove();mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;markers.current.forEach(m=>m.remove());markers.current=filtered.map(c=>{const v=c.metrics[year][metric],size=radius(v,metric)*2,el=document.createElement('button');el.className=`company-marker${selected.id===c.id?' is-selected':''}`;el.style.cssText=`width:${size}px;height:${size}px;--marker:${c.accent}`;el.setAttribute('aria-label',`${c.name} ${metricLabels[metric]} ${money(v,currency)}`);el.innerHTML=`<span>${c.ticker.slice(0,4)}</span>`;el.onclick=()=>setSelected(c);return new maplibregl.Marker({element:el}).setLngLat([c.lng,c.lat]).addTo(map)});},[filtered,year,metric,currency,selected]);
 const data=selected.metrics[year],top=[...filtered].sort((a,b)=>(b.metrics[year][metric]||0)-(a.metrics[year][metric]||0))[0];
 return <main className="app-shell"><header className="topbar"><a className="brand" href="#"><span className="brand-mark">◎</span><span>企業星図<small>GLOBAL COMPANY ATLAS</small></span></a><div className="header-note"><span className="live-dot"/>25社のデモデータ</div></header>
 <section className="control-deck" aria-label="表示条件"><label><span>年度</span><select value={year} onChange={e=>setYear(+e.target.value)}><option>2025</option><option>2024</option><option>2023</option></select></label><label><span>指標</span><select value={metric} onChange={e=>setMetric(e.target.value as MetricKey)}>{Object.entries(metricLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><span>業種</span><select value={industry} onChange={e=>setIndustry(e.target.value)}>{['すべての業種',...new Set(companies.map(c=>c.industry))].map(v=><option key={v}>{v}</option>)}</select></label><label><span>地域</span><select value={region} onChange={e=>setRegion(e.target.value)}>{['すべての地域',...new Set(companies.map(c=>c.region))].map(v=><option key={v}>{v}</option>)}</select></label><label><span>通貨</span><select value={currency} onChange={e=>setCurrency(e.target.value as keyof typeof rates)}>{Object.keys(rates).map(v=><option key={v}>{v}</option>)}</select></label><label className="search"><span>企業を検索</span><div><b>⌕</b><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="企業名 / ティッカー"/><kbd>⌘ K</kbd></div></label></section>
 <section className="map-stage"><div className="map-heading"><p>WORLD VIEW · {year}</p><h1>世界の企業を、<br/>ひと目で。</h1><span>{metricLabels[metric]}を円の大きさで比較しています</span></div><div ref={mapNode} className="map"/><div className="map-stat"><span>表示中</span><strong>{filtered.length}</strong><small>COMPANIES</small></div><div className="legend"><span>円の大きさ</span><i className="dot sm"/><i className="dot md"/><i className="dot lg"/><b>{metricLabels[metric]}</b></div></section>
 <aside className="company-card"><div className="company-head"><div className="monogram" style={{'--accent':selected.accent} as React.CSSProperties}>{selected.ticker.slice(0,2)}</div><div><p>{selected.ticker} · {selected.country}</p><h2>{selected.name}</h2><span>{selected.industry}</span></div></div><div className="hero-metric"><span>{metricLabels[metric]}</span><strong>{money(data[metric],currency)}</strong><small>USD基準 · 現在の為替レートで換算</small></div><div className="metric-grid">{(Object.keys(metricLabels) as MetricKey[]).map(k=><div key={k} className={k===metric?'active':''}><span>{metricLabels[k]}</span><b>{money(data[k],currency)}</b></div>)}</div><div className="rank"><span>現在のトップ</span><b>{top?.name||'—'}</b><em>{top?money(top.metrics[year][metric],currency):'—'}</em></div></aside>
 <footer><span>データはプロトタイプ用の参考値です</span><span>円のサイズはUSD値を基準に計算</span></footer></main>;
}
