'use client';
import { useEffect, useMemo, useRef, useState } from 'react';

type MetricKey='marketCap'|'revenue'|'operatingIncome'|'netIncome';
type Company={id:string;name:string;ticker:string;country:string;region:string;industry:string;lat:number;lng:number;accent:string;metrics:Record<number,Record<MetricKey,number|null>>};
const metricLabels:Record<MetricKey,string>={marketCap:'時価総額',revenue:'売上高',operatingIncome:'営業利益',netIncome:'純利益'};
const rates={USD:1,JPY:147.2,EUR:.86,CNY:7.13,KRW:1388,GBP:.74};
const symbols={USD:'$',JPY:'¥',EUR:'€',CNY:'CN¥',KRW:'₩',GBP:'£'};
const base=[
['nvidia','NVIDIA','NVDA','アメリカ','北米','半導体',37.37,-121.96,'#7CFF6B'],['apple','Apple','AAPL','アメリカ','北米','ソフトウェア',37.33,-122.01,'#8BA7FF'],['microsoft','Microsoft','MSFT','アメリカ','北米','ソフトウェア',47.64,-122.13,'#5DD4FF'],['alphabet','Alphabet','GOOGL','アメリカ','北米','ソフトウェア',37.42,-122.08,'#FFCA65'],['amazon','Amazon','AMZN','アメリカ','北米','小売',47.62,-122.34,'#FF9B55'],['meta','Meta','META','アメリカ','北米','ソフトウェア',37.48,-122.15,'#6E8EFF'],['broadcom','Broadcom','AVGO','アメリカ','北米','半導体',37.40,-121.98,'#BC8CFF'],['tesla','Tesla','TSLA','アメリカ','北米','自動車',30.22,-97.62,'#FF6B6B'],['jpm','JPMorgan Chase','JPM','アメリカ','北米','金融',40.76,-73.97,'#7DE0B1'],['walmart','Walmart','WMT','アメリカ','北米','小売',36.37,-94.21,'#68D9C4'],['eli','Eli Lilly','LLY','アメリカ','北米','医薬品',39.77,-86.16,'#FF86B7'],['aramco','Saudi Aramco','2222','サウジアラビア','中東','エネルギー',26.31,50.12,'#F4C95D'],['sap','SAP','SAP','ドイツ','欧州','ソフトウェア',49.29,8.64,'#72B7FF'],['asml','ASML','ASML','オランダ','欧州','半導体',51.44,5.48,'#B58CFF'],['novo','Novo Nordisk','NVO','デンマーク','欧州','医薬品',55.81,12.51,'#FF86B7'],['toyota','Toyota Motor','7203.T','日本','アジア','自動車',35.08,137.16,'#FF7171'],['sony','Sony Group','6758.T','日本','アジア','その他',35.46,139.62,'#C3A6FF'],['tel','Tokyo Electron','8035.T','日本','アジア','半導体',35.68,139.77,'#7CFF6B'],['tsmc','TSMC','TSM','台湾','アジア','半導体',24.78,121,'#67F5B7'],['samsung','Samsung Electronics','005930','韓国','アジア','半導体',37.26,127.03,'#81A1FF'],['tencent','Tencent','0700.HK','中国','アジア','ソフトウェア',22.54,114.06,'#5DD4FF'],['alibaba','Alibaba','BABA','中国','アジア','小売',30.19,120.19,'#FF9B55'],['byd','BYD','1211.HK','中国','アジア','自動車',22.60,114.05,'#FF7171'],['reliance','Reliance Industries','RELIANCE','インド','アジア','エネルギー',19.06,72.87,'#F4C95D'],['hdfc','HDFC Bank','HDB','インド','アジア','金融',19.17,72.87,'#7DE0B1']];
const caps=[4300,3900,3800,2500,2300,1900,1650,1050,820,790,760,1800,380,420,310,330,150,125,1200,360,690,280,155,210,185];
const revRatios=[.3,.31,.36,.14,.31,.08,.1,.09,.22,.86,.08,.25,.12,.08,.11,.9,.55,.09,.07,.45,.18,.48,.3,.42,.24];
const companies:Company[]=base.map((row,i)=>{const [id,name,ticker,country,region,industry,lat,lng,accent]=row as [string,string,string,string,string,string,number,number,string];const cap=caps[i],rev=cap*revRatios[i];const make=(f:number)=>({marketCap:cap*f,revenue:rev*f,operatingIncome:rev*.18*f,netIncome:rev*.14*f});return{id,name,ticker,country,region,industry,lat,lng,accent,metrics:{2023:make(.72),2024:make(.86),2025:make(1)}}});
function money(v:number|null,c:keyof typeof rates){if(v==null)return'—';const x=v*rates[c],local=c==='JPY'||c==='KRW';return`${symbols[c]}${(local?x/1000:x).toFixed(x>=100?0:1)} ${c==='JPY'?'兆円':c==='KRW'?'조원':'B'}`}
function radius(v:number|null,m:MetricKey){if(!v)return 0;return Math.max(9,Math.min(52,Math.sqrt(v)*.72*(m==='marketCap'?1:m==='revenue'?1.55:3.2)))}

function FilterMenu({id,label,value,options,open,onToggle,onChange}:{id:string;label:string;value:string;options:{value:string;label:string}[];open:boolean;onToggle:()=>void;onChange:(value:string)=>void}){
 return <div className={`filter-menu ${open?'is-open':''}`}><button type="button" className="filter-trigger" onClick={onToggle} aria-expanded={open}><span>{label}</span><strong>{value}</strong><i>▾</i></button>{open&&<div className="filter-panel" role="menu">{options.map(option=><button type="button" key={option.value} className={option.label===value?'active':''} onClick={()=>onChange(option.value)}>{option.label}<span>{option.label===value?'✓':''}</span></button>)}</div>}</div>;
}

type WorldGeometry={type:'Polygon'|'MultiPolygon';coordinates:number[][][]|number[][][][]};
type WorldData={features:{geometry:WorldGeometry}[]};
function WorldCanvas({items,year,metric,selected,onSelect,theme}:{items:Company[];year:number;metric:MetricKey;selected:Company|null;onSelect:(company:Company)=>void;theme:'dark'|'light'}){
 const canvas=useRef<HTMLCanvasElement>(null),[world,setWorld]=useState<WorldData|null>(null),points=useRef<{company:Company;x:number;y:number;r:number}[]>([]),[view,setView]=useState({scale:1,x:0,y:0}),drag=useRef<{x:number;y:number;originX:number;originY:number;moved:boolean}|null>(null);
 useEffect(()=>{fetch('/countries.geojson').then(r=>r.json()).then(setWorld).catch(()=>setWorld({features:[]}));},[]);
 useEffect(()=>{
  const el=canvas.current;if(!el)return;
  const draw=()=>{
   const box=el.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);
   el.width=box.width*dpr;el.height=box.height*dpr;
   const ctx=el.getContext('2d');if(!ctx)return;ctx.scale(dpr,dpr);
   const w=box.width,h=box.height,centerLng=140,project=(lng:number,lat:number)=>{const relative=((lng-centerLng+540)%360)-180,bx=(relative+180)/360*w,by=(90-lat)/180*h;return{x:(bx-w/2)*view.scale+w/2+view.x,y:(by-h/2)*view.scale+h/2+view.y}};
   ctx.fillStyle=theme==='dark'?'#0b0f14':'#f5f6f4';ctx.fillRect(0,0,w,h);ctx.fillStyle=theme==='dark'?'#18212a':'#dfe4df';ctx.strokeStyle=theme==='dark'?'#43525f':'#aab5ad';ctx.lineWidth=.65;
   const polygon=(rings:number[][][])=>{ctx.beginPath();rings.forEach(ring=>{let previousX:number|undefined;ring.forEach(([lng,lat],i)=>{const p=project(lng,lat);if(i===0||previousX===undefined||Math.abs(p.x-previousX)>w/2)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);previousX=p.x})});ctx.fill('evenodd');ctx.stroke()};
   world?.features.forEach(f=>{if(f.geometry.type==='Polygon')polygon(f.geometry.coordinates as number[][][]);else (f.geometry.coordinates as number[][][][]).forEach(polygon)});
   points.current=items.flatMap(company=>{const value=company.metrics[year]?.[metric]??null,r=radius(value,metric);if(!r)return[];const p=project(company.lng,company.lat),grad=ctx.createRadialGradient(p.x,p.y,1,p.x,p.y,r);grad.addColorStop(0,company.accent+'aa');grad.addColorStop(1,company.accent+'22');ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle=company.accent;ctx.lineWidth=selected?.id===company.id?2:1;ctx.stroke();if(r>15){ctx.fillStyle='#fff';ctx.font='700 8px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(company.ticker.slice(0,4),p.x,p.y)}return[{company,x:p.x,y:p.y,r}]});
  };
  draw();const resize=new ResizeObserver(draw);resize.observe(el);return()=>resize.disconnect();
 },[world,items,year,metric,selected,theme,view]);
 return <canvas ref={canvas} className="map-canvas" aria-label="世界企業マップ" onWheel={e=>{e.preventDefault();const rect=e.currentTarget.getBoundingClientRect(),cx=e.clientX-rect.left,cy=e.clientY-rect.top;setView(old=>{const next=Math.max(1,Math.min(6,old.scale*(e.deltaY<0?.85:1.18)));if(next===1)return{scale:1,x:0,y:0};return{scale:next,x:cx-rect.width/2-(cx-rect.width/2-old.x)/old.scale*next,y:cy-rect.height/2-(cy-rect.height/2-old.y)/old.scale*next}})}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,originX:view.x,originY:view.y,moved:false}}} onPointerMove={e=>{if(!drag.current)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;if(Math.abs(dx)+Math.abs(dy)>3)drag.current.moved=true;setView(v=>({...v,x:drag.current!.originX+dx,y:drag.current!.originY+dy}))}} onPointerUp={e=>{const moved=drag.current?.moved;drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId);if(moved)return;const rect=e.currentTarget.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,hit=[...points.current].reverse().find(p=>Math.hypot(p.x-x,p.y-y)<=p.r);if(hit)onSelect(hit.company)}}/>;
}

export default function Home(){
 const[year,setYear]=useState(2025),[metric,setMetric]=useState<MetricKey>('marketCap'),[industry,setIndustry]=useState('すべての業種'),[region,setRegion]=useState('すべての地域'),[currency,setCurrency]=useState<keyof typeof rates>('JPY'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Company|null>(null),[theme,setTheme]=useState<'dark'|'light'>('dark'),[openFilter,setOpenFilter]=useState<string|null>(null);
 const filtered=useMemo(()=>companies.filter(c=>(industry==='すべての業種'||c.industry===industry)&&(region==='すべての地域'||c.region===region)&&`${c.name} ${c.ticker}`.toLowerCase().includes(query.toLowerCase())),[industry,region,query]);
 const visibleCount=filtered.filter(c=>c.metrics[year]?.[metric]!=null).length;
 const data=selected?.metrics[year],top=[...filtered].sort((a,b)=>(b.metrics[year]?.[metric]||0)-(a.metrics[year]?.[metric]||0))[0];
 const years=Array.from({length:26},(_,i)=>2025-i);
 const metricOptions=Object.entries(metricLabels).map(([value,label])=>({value,label}));
 const industryOptions=['すべての業種',...new Set(companies.map(c=>c.industry))].map(value=>({value,label:value}));
 const regionOptions=['すべての地域',...new Set(companies.map(c=>c.region))].map(value=>({value,label:value}));
 const currencyOptions=[{value:'USD',label:'米ドル (USD)'},{value:'JPY',label:'日本円 (JPY)'},{value:'EUR',label:'ユーロ (EUR)'}];
 return <main className="app-shell" data-theme={theme}><header className="topbar"><a className="brand" href="#"><span className="brand-mark">◎</span><span>企業星図</span></a><div className="header-search"><b>⌕</b><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="企業名 / ティッカーを検索"/></div><div className="header-actions"><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="表示テーマを切り替え">{theme==='dark'?'☀︎':'☾'}</button><div className="header-note"><span className="live-dot"/>25社</div></div></header>
 <section className="control-deck" aria-label="表示条件">{openFilter&&<button className="filter-backdrop" aria-label="メニューを閉じる" onClick={()=>setOpenFilter(null)}/>}<FilterMenu id="year" label="年度" value={String(year)} options={years.map(v=>({value:String(v),label:String(v)}))} open={openFilter==='year'} onToggle={()=>setOpenFilter(openFilter==='year'?null:'year')} onChange={v=>{setYear(+v);setOpenFilter(null)}}/><FilterMenu id="metric" label="指標" value={metricLabels[metric]} options={metricOptions} open={openFilter==='metric'} onToggle={()=>setOpenFilter(openFilter==='metric'?null:'metric')} onChange={v=>{setMetric(v as MetricKey);setOpenFilter(null)}}/><FilterMenu id="industry" label="業種" value={industry} options={industryOptions} open={openFilter==='industry'} onToggle={()=>setOpenFilter(openFilter==='industry'?null:'industry')} onChange={v=>{setIndustry(v);setOpenFilter(null)}}/><FilterMenu id="region" label="地域" value={region} options={regionOptions} open={openFilter==='region'} onToggle={()=>setOpenFilter(openFilter==='region'?null:'region')} onChange={v=>{setRegion(v);setOpenFilter(null)}}/><FilterMenu id="currency" label="通貨" value={currencyOptions.find(o=>o.value===currency)?.label||currency} options={currencyOptions} open={openFilter==='currency'} onToggle={()=>setOpenFilter(openFilter==='currency'?null:'currency')} onChange={v=>{setCurrency(v as keyof typeof rates);setOpenFilter(null)}}/></section>
 <section className="map-stage"><div className="map-heading"><p>{year} · {metricLabels[metric]}</p><h1>世界企業マップ</h1><span>日本を中心に企業規模を表示</span></div><WorldCanvas items={filtered} year={year} metric={metric} selected={selected} onSelect={setSelected} theme={theme}/><div className="map-stat"><span>表示中</span><strong>{visibleCount}</strong><small>社</small></div><div className="legend"><span>円の大きさ</span><i className="dot sm"/><i className="dot md"/><i className="dot lg"/><b>{metricLabels[metric]}</b></div></section>
 {selected&&data&&<aside className="company-card"><button className="card-close" onClick={()=>setSelected(null)} aria-label="企業詳細を閉じる">×</button><div className="company-head"><div className="monogram" style={{'--accent':selected.accent} as React.CSSProperties}>{selected.ticker.slice(0,2)}</div><div><p>{selected.ticker} · {selected.country}</p><h2>{selected.name}</h2><span>{selected.industry}</span></div></div><div className="hero-metric"><span>{metricLabels[metric]}</span><strong>{money(data[metric],currency)}</strong><small>USD基準 · 現在の為替レートで換算</small></div><div className="metric-grid">{(Object.keys(metricLabels) as MetricKey[]).map(k=><div key={k} className={k===metric?'active':''}><span>{metricLabels[k]}</span><b>{money(data[k],currency)}</b></div>)}</div><div className="rank"><span>現在のトップ</span><b>{top?.name||'—'}</b><em>{top?money(top.metrics[year]?.[metric]??null,currency):'—'}</em></div></aside>}
 <footer><span>データはプロトタイプ用の参考値です</span><span>円のサイズはUSD値を基準に計算</span></footer></main>;
}
